customersSupportSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include(('supportSystem.urls'), namespace='https'))
)

supportSystem/urls.py
from django.urls import re_path
from supportSystem.views import staff, login


app_name = 'supportSystem'

base64_pattern = r'(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'

urlpatterns = [
    re_path(r'^dashboard/$',
        staff.dashboard,
        name='dashboard'),

    re_path(r'^tickets/$',
        staff.ticket_list,
        name='list'),

    re_path(r'^tickets/update/$',
        staff.mass_update,
        name='mass_update'),


    re_path(r'^tickets/(?P<ticket_id>[0-9]+)/$',
        staff.view_ticket,
        name='view'),

    re_path(r'^tickets/(?P<ticket_id>[0-9]+)/followup_edit/(?P<followup_id>[0-9]+)/$',
        staff.followup_edit,
        name='followup_edit'),

    re_path(r'^tickets/(?P<ticket_id>[0-9]+)/followup_delete/(?P<followup_id>[0-9]+)/$',
        staff.followup_delete,
        name='followup_delete'),

    re_path(r'^tickets/(?P<ticket_id>[0-9]+)/update/$',
        staff.update_ticket,
        name='update'),

    re_path(r'^tickets/(?P<ticket_id>[0-9]+)/delete/$',
        staff.delete_ticket,
        name='delete'),


    re_path(r'^tickets/(?P<ticket_id>[0-9]+)/attachment_delete/(?P<attachment_id>[0-9]+)/$',
        staff.attachment_del,
        name='attachment_del'),


    re_path(r'^reports/$',
        staff.report_index,
        name='report_index'),

    re_path(r'^reports/(?P<report>\w+)/$',
        staff.run_report,
        name='run_report'),


    re_path(r'^datatables_ticket_list/(?P<query>{})$'.format(base64_pattern),
        staff.datatables_ticket_list,
        name="datatables_ticket_list"),

]

urlpatterns += [
    re_path(r'^$',
        staff.homepage,
        name='home'),
]


urlpatterns += [
    re_path(r'^login/$', login.loginPage, name='login'),
    re_path(r'^authenticate/$', login.auth, name='signin'),
    re_path(r'^callback/$', login.callback, name='callback'),
    re_path(r'^signout/$', login.signout, name='signout'),
]

supportSystem/forms.py
import logging
from django.core.exceptions import ValidationError
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from supportSystem.models import (Ticket, FollowUp)


logger = logging.getLogger(__name__)
User = get_user_model()

CUSTOMFIELD_TO_FIELD_DICT = {
    'boolean': forms.BooleanField,
    'date': forms.DateField,
    'time': forms.TimeField,
    'datetime': forms.DateTimeField,
    'email': forms.EmailField,
    'url': forms.URLField,
    'ipaddress': forms.GenericIPAddressField,
    'slug': forms.SlugField,
}

CUSTOMFIELD_DATE_FORMAT = "%Y-%m-%d"
CUSTOMFIELD_TIME_FORMAT = "%H:%M:%S"
CUSTOMFIELD_DATETIME_FORMAT = f"{CUSTOMFIELD_DATE_FORMAT} {CUSTOMFIELD_TIME_FORMAT}"


class EditFollowUpForm(forms.ModelForm):

    class Meta:
        model = FollowUp
        exclude = ('date', 'user',)

    def __init__(self, *args, **kwargs):
        super(EditFollowUpForm, self).__init__(*args, **kwargs)
        self.fields["ticket"].queryset = Ticket.objects.filter(status__in=(Ticket.OPEN_STATUS, Ticket.REOPENED_STATUS))


class MultipleTicketSelectForm(forms.Form):
    tickets = forms.ModelMultipleChoiceField(
        label=_('Tickets to merge'),
        queryset=Ticket.objects.filter(merged_to=None),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'})
    )

    def clean_tickets(self):
        tickets = self.cleaned_data.get('tickets')
        if len(tickets) < 2:
            raise ValidationError(_('Please choose at least 2 tickets.'))
        if len(tickets) > 4:
            raise ValidationError(_('Impossible to merge more than 4 tickets...'))
        queues = tickets.order_by('queue').distinct().values_list('queue', flat=True)
        if len(queues) != 1:
            raise ValidationError(_('All selected tickets must share the same queue in order to be merged.'))
        return tickets

supportSystem/views/login.py
from django.contrib.auth import login
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..auth_helper import get_sign_in_flow, get_token_from_code, store_user, remove_user_and_token, get_token, \
    get_sys_user, get_logout_url
from ..graph_helper import *
from django.contrib.auth import logout


def home(request):
    context = initialize_context(request)
    return HttpResponseRedirect(reverse('supportSystem:home'), context)


def initialize_context(request):
    context = {}
    error = request.session.pop('flash_error', None)
    if error != None:
        context['errors'] = []
        context['errors'].append(error)
    # Check for user in the session
    context['user'] = request.session.get('user', {'is_authenticated': False})
    return context


def loginPage(request):
    if request.method == 'POST':
        return HttpResponseRedirect(reverse('supportSystem:signin'))
    return render(request, 'supportSystem/login.html')


def auth(request):
    # Get the sign-in flow
    flow = get_sign_in_flow()
    # Save flow
    try:
        request.session['auth_flow'] = flow
    except Exception as e:
        print(e)
    # Redirect to the Azure
    return HttpResponseRedirect(flow['auth_uri'])


def signout(request):
    logout(request)
    redirect = request.build_absolute_uri(reverse('supportSystem:home'))
    logout_url = get_logout_url(redirect)
    return HttpResponseRedirect(logout_url)


def callback(request):
    result = get_token_from_code(request)
    user = get_user(result['access_token'])
    group = get_group(result['access_token'])
    if user and group:
        store_user(request, user)
        sys_user = get_sys_user(user, group)
        login(user=sys_user, request=request)
        return HttpResponseRedirect(reverse('supportSystem:dashboard'))
    else:
        return HttpResponseRedirect(reverse('supportSystem:login'))

supportSystem/views/staff.py
from copy import deepcopy
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect,  JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import gettext_lazy as _
from django.utils.html import escape
from django.utils import timezone
from supportSystem.query import (
    get_query_class,
    query_to_base64
)
from supportSystem.user import HelpdeskUser
from supportSystem.decorators import (
    helpdesk_staff_member_required,
    is_helpdesk_staff
)
from supportSystem.forms import EditFollowUpForm, CUSTOMFIELD_DATE_FORMAT

from supportSystem.lib import (
    safe_template_context,
    process_attachments,
    queue_template_context,
)
from supportSystem.models import (
    Ticket, Queue, FollowUp, TicketChange, FollowUpAttachment
)
from customersSupportSystem import settings as helpdesk_settings
from rest_framework import status
from rest_framework.decorators import api_view
from datetime import date, datetime, timedelta
import re

User = get_user_model()
Query = get_query_class()

staff_member_required = user_passes_test(
    lambda u: u.is_authenticated and u.is_active and u.is_staff)


def _get_queue_choices(queues):
    queue_choices = []
    if len(queues) > 1:
        queue_choices = [('', '--------')]
    queue_choices += [(q.id, q.title) for q in queues]
    return queue_choices


@helpdesk_staff_member_required
def dashboard(request):
    tickets_per_page = 25
    user_tickets_page = request.GET.get(_('ut_page'), 1)
    user_tickets_closed_resolved_page = request.GET.get(_('utcr_page'), 1)
    all_tickets_reported_by_current_user_page = request.GET.get(_('atrbcu_page'), 1)

    huser = HelpdeskUser(request.user)
    active_tickets = Ticket.objects.select_related('queue').exclude(
        status__in=[Ticket.CLOSED_STATUS, Ticket.RESOLVED_STATUS],
    )

    tickets = active_tickets.filter(
        assigned_to=request.user,
    )

    tickets_closed_resolved = Ticket.objects.select_related('queue').filter(
        assigned_to=request.user,
        status__in=[Ticket.CLOSED_STATUS, Ticket.RESOLVED_STATUS])

    user_queues = huser.get_queues()

    unassigned_tickets = active_tickets.filter(
        assigned_to__isnull=True,
        queue__in=user_queues
    )

    all_tickets_reported_by_current_user = ''
    email_current_user = request.user.email
    if email_current_user:
        all_tickets_reported_by_current_user = Ticket.objects.select_related('queue').filter(
            submitter_email=email_current_user,
        ).order_by('status')

    tickets_in_queues = Ticket.objects.filter(
        queue__in=user_queues,
    )
    basic_ticket_stats = calc_basic_ticket_stats(tickets_in_queues)

    paginator = Paginator(
        tickets, tickets_per_page)
    try:
        tickets = paginator.page(user_tickets_page)
    except PageNotAnInteger:
        tickets = paginator.page(1)
    except EmptyPage:
        tickets = paginator.page(
            paginator.num_pages)

    paginator = Paginator(
        tickets_closed_resolved, tickets_per_page)
    try:
        tickets_closed_resolved = paginator.page(
            user_tickets_closed_resolved_page)
    except PageNotAnInteger:
        tickets_closed_resolved = paginator.page(1)
    except EmptyPage:
        tickets_closed_resolved = paginator.page(
            paginator.num_pages)

    paginator = Paginator(
        all_tickets_reported_by_current_user, tickets_per_page)
    try:
        all_tickets_reported_by_current_user = paginator.page(
            all_tickets_reported_by_current_user_page)
    except PageNotAnInteger:
        all_tickets_reported_by_current_user = paginator.page(1)
    except EmptyPage:
        all_tickets_reported_by_current_user = paginator.page(
            paginator.num_pages)

    return render(request, 'supportSystem/dashboard.html', {
        'user_tickets': tickets,
        'user_tickets_closed_resolved': tickets_closed_resolved,
        'unassigned_tickets': unassigned_tickets,
        'all_tickets_reported_by_current_user': all_tickets_reported_by_current_user,
        'basic_ticket_stats': basic_ticket_stats,
    })


dashboard = staff_member_required(dashboard)


def ticket_perm_check(request, ticket):
    huser = HelpdeskUser(request.user)
    if not huser.can_access_queue(ticket.queue):
        raise PermissionDenied()
    if not huser.can_access_ticket(ticket):
        raise PermissionDenied()


@helpdesk_staff_member_required
def delete_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)
    ticket_perm_check(request, ticket)

    if request.method == 'GET':
        return render(request, 'supportSystem/delete_ticket.html', {
            'ticket': ticket,
            'next': request.GET.get('next', 'home')
        })
    else:
        ticket.delete()
        redirect_to = 'supportSystem:dashboard'
        if request.POST.get('next') == 'dashboard':
            redirect_to = 'supportSystem:dashboard'
        return HttpResponseRedirect(reverse(redirect_to))


delete_ticket = staff_member_required(delete_ticket)


@helpdesk_staff_member_required
def followup_edit(request, ticket_id, followup_id):
    followup = get_object_or_404(FollowUp, id=followup_id)
    ticket = get_object_or_404(Ticket, id=ticket_id)
    ticket_perm_check(request, ticket)

    if request.method == 'GET':
        form = EditFollowUpForm(initial={
            'title': escape(followup.title),
            'ticket': followup.ticket,
            'comment': escape(followup.comment),
            'public': followup.public,
            'new_status': followup.new_status
        })


        return render(request, 'supportSystem/followup_edit.html', {
            'followup': followup,
            'ticket': ticket,
            'form': form,
        })
    elif request.method == 'POST':
        form = EditFollowUpForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            _ticket = form.cleaned_data['ticket']
            comment = form.cleaned_data['comment']
            public = form.cleaned_data['public']
            new_status = form.cleaned_data['new_status']

            old_date = followup.date
            new_followup = FollowUp(title=title, date=old_date, ticket=_ticket,
                                    comment=comment, public=public,
                                    new_status=new_status)
            if followup.user:
                new_followup.user = followup.user
            new_followup.save()

            attachments = FollowUpAttachment.objects.filter(followup=followup)
            for attachment in attachments:
                attachment.followup = new_followup
                attachment.save()
            # delete old followup
            followup.delete()
        return HttpResponseRedirect(reverse('supportSystem:view', args=[ticket.id]))


followup_edit = staff_member_required(followup_edit)


@helpdesk_staff_member_required
def followup_delete(request, ticket_id, followup_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('supportSystem:view', args=[ticket.id]))

    followup = get_object_or_404(FollowUp, id=followup_id)
    followup.delete()
    return HttpResponseRedirect(reverse('supportSystem:view', args=[ticket.id]))


followup_delete = staff_member_required(followup_delete)


@helpdesk_staff_member_required
def view_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)
    ticket_perm_check(request, ticket)

    if 'take' in request.GET:
        request.POST = {
            'owner': request.user.id,
            'public': 1,
            'title': ticket.title,
            'comment': ''
        }
        return update_ticket(request, ticket_id)

    if 'close' in request.GET and ticket.status == Ticket.RESOLVED_STATUS:
        if not ticket.assigned_to:
            owner = 0
        else:
            owner = ticket.assigned_to.id

        request.POST = {
            'new_status': Ticket.CLOSED_STATUS,
            'public': 1,
            'owner': owner,
            'title': ticket.title,
            'comment': _('Accepted resolution and closed ticket'),
        }

        return update_ticket(request, ticket_id)

    users = User.objects.filter(is_active=True, is_staff=True).order_by(User.USERNAME_FIELD)

    return render(request, 'supportSystem/ticket.html', {
        'ticket': ticket,
        'active_users': users,
        'priorities': Ticket.PRIORITY_CHOICES,
    })


def update_ticket(request, ticket_id, public=False):
    ticket = None

    if not (public or (
            request.user.is_authenticated and
            request.user.is_active and
            is_helpdesk_staff(request.user))):

        key = request.POST.get('key')
        email = request.POST.get('mail')

        if key and email:
            ticket = Ticket.objects.get(
                id=ticket_id,
                submitter_email__iexact=email,
                secret_key__iexact=key
            )

        if not ticket:
            return HttpResponseRedirect(
                '%s?next=%s' % (reverse('supportSystem:login'), request.path)
            )

    if not ticket:
        ticket = get_object_or_404(Ticket, id=ticket_id)

    date_re = re.compile(
        r'(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<year>\d{4})$'
    )

    comment = request.POST.get('comment', '')
    new_status = int(request.POST.get('new_status', ticket.status))
    title = request.POST.get('title', '')
    public = request.POST.get('public', False)
    owner = int(request.POST.get('owner', -1))
    priority = int(request.POST.get('priority', ticket.priority))

supportSystem/templates/supportSystem/include/alert_form_errors.html
{% load i18n %}

<div class="alert alert-danger alert-dismissible fade show" role="alert">
      {% trans "This form has errors" %}.
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
</div>

supportSystem/templates/supportSystem/include/priority.html
{% load i18n %}
{% load static %}
<br>
<link rel="stylesheet" type="text/css", href="{% static 'css/cards.css' %}">
<div class="row">

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="ticket-30">
                <div class="card-header">
                    <a class="card-link" href="{% url 'supportSystem:list' %}?{{  basic_ticket_stats.open_ticket_stats.0.1 }}" class="card-title" >{% trans "Critical priority tickets" %}</a>
                </div>
                <div class="card-body" >
                    <h3 class="card-title" >{{ basic_ticket_stats.open_ticket_stats.0.2 }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="ticket-3060">
                <div class="card-header">
                    <a class="card-link" href="{% url 'supportSystem:list' %}?{{  basic_ticket_stats.open_ticket_stats.1.1 }}">{% trans "High priority tickets" %}</a>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ basic_ticket_stats.open_ticket_stats.1.2 }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="ticket-60">
                <div class="card-header">
                     <a class="card-link" href="{% url 'supportSystem:list' %}?{{  basic_ticket_stats.open_ticket_stats.2.1 }}">{% trans "Medium priority tickets" %}</a>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ basic_ticket_stats.open_ticket_stats.2.2 }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>

supportSystem/templates/supportSystem/include/status.html
{% load i18n %}
{% load static %}
<br>
<link rel="stylesheet" type="text/css", href="{% static 'css/cards.css' %}">
<div class="row">

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="ticket-30">
                <div class="card-header">
                    <a class="card-link" href="{% url 'supportSystem:list' %}?{{  basic_ticket_stats.ticket_status.0.1 }}" class="card-title" >{% trans "Opened Tickets" %}</a>
                </div>
                <div class="card-body" >
                    <h3 class="card-title" >{{ basic_ticket_stats.ticket_status.0.2 }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="ticket-3060">
                <div class="card-header">
                    <a class="card-link" href="{% url 'supportSystem:list' %}?{{  basic_ticket_stats.ticket_status.1.1 }}">{% trans "Resolved Tickets" %}</a>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ basic_ticket_stats.ticket_status.1.2 }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="ticket-60">
                <div class="card-header">
                     <a class="card-link" href="{% url 'supportSystem:list' %}?{{  basic_ticket_stats.ticket_status.2.1 }}">{% trans "Closed Tickets" %}</a>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ basic_ticket_stats.ticket_status.2.2 }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>

supportSystem/templates/supportSystem/include/tickets.html
{% load i18n humanize %}

<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        {% if ticket_list_caption %}{{ ticket_list_caption }}{% else %}{% trans "Your tickets" %}{% endif %}
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-bordered table-sm table-striped" id="dataTable" width="100%" cellspacing="0">
            <thead class="thead-light">
                <tr>
                    <th>{% trans "Ticket" %}</th>
                    <th>{% trans "Priority" %}</th>
                    <th>{% trans "Queue" %}</th>
                    <th>{% trans "Status" %}</th>
                    <th>{% trans "Updated" %}</th>
                    <th>{% trans "Actions" %}</th>

                </tr>
            </thead>
            <tbody>
                {% for ticket in ticket_list %}
                <tr class="{{ ticket.get_priority_css_class }}">
                    <td > {{ ticket.title }}</td>
                    <td>{{ ticket.priority }}</td>
                    <td>{{ ticket.queue }}</td>
                    <td>{{ ticket.get_status }}</td>
                    <td><span title='{{ ticket.modified|date:"DATETIME_FORMAT" }}'>{{ ticket.modified|naturaltime }}</span></td>
                    <td><a class="btn btn-sm btn-info" href="{{ ticket.get_absolute_url }}" >{% trans "View" %}</a>
                    <a class="btn btn-sm btn-danger" href="{% url 'supportSystem:delete' ticket.id %}">{% trans "Delete" %}</a>
                    </td>

                </tr>
                {% empty %}
                <tr>{% if ticket_list_empty_message %}<td colspan='6'>{{ ticket_list_empty_message }}</td>{% else %}<td colspan='6'>{% trans "No waiting tickets" %}</td>{% endif %}</tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
        <!-- /.table-responsive -->
        {% if ticket_list.has_other_pages %}
            <ul class="pagination">
            <!-- if we aren't on page one, go back to start and go back one controls -->
            {% if ticket_list.has_previous %}
                <li><a href="?{{ page_var }}=1">&laquo;&laquo;</a></li>
                <li><a href="?{{ page_var }}={{ ticket_list.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;&laquo;</span></li>
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            <!-- other pages, set thresh to the number to show before and after active -->
            {% with 5 as thresh %}
            {% for i in ticket_list.paginator.page_range %}
            {% if ticket_list.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% elif i <= ticket_list.number|add:5 and i >= ticket_list.number|add:-5 %}
                <li><a href="?{{ page_var }}={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% endwith %}
            <!-- if we aren't on the last page, go forward one and go to end controls -->
            {% if ticket_list.has_next %}
                <li><a href="?{{ page_var }}={{ ticket_list.next_page_number }}">&raquo;</a></li>
                <li><a href="?{{ page_var }}={{ ticket_list.paginator.num_pages }}">&raquo;&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
                <li class="disabled"><span>&raquo;&raquo;</span></li>
            {% endif %}
            </ul>
        {% endif %}
    </div>
    <div class="card-footer small text-muted">Listing {{ ticket_list|length }} ticket(s).</div>
</div>

supportSystem/templates/supportSystem/include/unassigned.html
{% load i18n humanize %}

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        {% trans "Unassigned tickets" %}
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-sm table-striped" id="dataTable" width="100%" cellspacing="0">
                <thead class="thead-light">
                    <tr>
                      <th>{% trans "Ticket" %}</th>
                      <th>{% trans "Priority" %}</th>
                      <th>{% trans "Queue" %}</th>
                      <th>{% trans "Created" %}</th>
                      <th>{% trans "Actions" %}</th>
                    </tr>
                </thead>
                <tbody>
                {% for ticket in unassigned_tickets %}
                    <tr class="{{ ticket.get_priority_css_class }}">
                        <td >{{ ticket.title }} </td>
                        <td>{{ ticket.priority }}</td>
                        <td>{{ ticket.queue }}</td>
                        <td><span title='{{ ticket.created|date:"DATETIME_FORMAT" }}'>{{ ticket.created|naturaltime }}</span></td>
                        <td >
                          <a class="btn btn-sm btn-info" href="{{ ticket.get_absolute_url }}" >View</a>
                          <a href='{{ ticket.get_absolute_url }}?take'><button class='btn btn-primary btn-sm'><i class="fas fa-hand-paper"></i>&nbsp;{% trans "Take" %}</button></a>
                          <a href='{% url 'supportSystem:delete' ticket.id %}?next=dashboard'><button class='btn btn-danger btn-sm'><i class="fas fa-trash"></i>&nbsp;{% trans "Delete" %}</button></a>
                        </td>
                    </tr>
                {% empty %}
                    <tr><td colspan='6'>{% trans "No unassigned tickets" %}</td></tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Listing {{ unassigned_tickets|length }} ticket(s).</div>
</div>